<div class="CmApp-Bar-container CmApp-Bar-top_bar noselect nav-area ">
    <div class="nav-logo " id="ktlogo" title="返回管理平台" data-type="toKtuHome">
        <svg class="nav-logo-icon">
            <use xlink:href="#svg-nav-logo">
            </use>
        </svg>
    </div>
    <div class="nav-btn CmApp-Tools-undo has-tips" id="CmApp-Tools-undo" tips="撤销（Z）" data-type="undo" style="
    width: 82px;
">
        <svg class="nav-icon">
            <use class="nav-icon-use" xlink:href="#svg-nav-back">
            </use>
        </svg>
        <div class="btn-name">
            后退
        </div>
    </div>
    <div class="nav-btn CmApp-Tools-redo has-tips" id="CmApp-Tools-redo" tips="重做（Y）" data-type="redo" style="
    width: 82px;
">
        <svg class="nav-icon">
            <use class="nav-icon-use" xlink:href="#svg-nav-forward">
            </use>
        </svg>
        <div class="btn-name">
            前进
        </div>
    </div>
    <div class="nav-split">
    </div>
    <div class="nav-btn CmApp-Tools-green green-tool has-tips" id="green-tool" data-type="savePath" tips="保留工具（空格键）">
        <svg class="nav-icon">
            <use class="nav-icon-use" xlink:href="#svg-nav-green">
            </use>
        </svg>
        <div class="btn-name">
            保留
        </div>
    </div>
    <div class="nav-btn CmApp-Tools-red red-tool has-tips" id="red-tool" data-type="delPath" tips="删除工具（空格键）">
        <svg class="nav-icon">
            <use class="nav-icon-use" xlink:href="#svg-nav-red">
            </use>
        </svg>
        <div class="btn-name">
            删除
        </div>
    </div>
    <div class="nav-btn CmApp-Tools-red erase-tool has-tips" id="erase-tool" data-type="eraserPath" tips="橡皮擦（X）">
        <svg class="nav-icon">
            <use class="nav-icon-use" xlink:href="#svg-nav-erase">
            </use>
        </svg>
        <div class="btn-name">
            橡皮檫
        </div>
    </div>
    <div class="nav-btn CmApp-Tools-red sword-tool has-tips" id="sword-tool" tips="修边工具（S）">
        <svg class="nav-icon">
            <use class="nav-icon-use" xlink:href="#svg-nav-sword">
            </use>
        </svg>
        <div class="btn-name">
            修边工具
        </div>
    </div>
    <div class="nav-btn CmApp-Tools-red pan-tool has-tips" id="pan-tool" data-type="handTool" tips="平移工具（Shift）">
        <svg class="nav-icon">
            <use class="nav-icon-use" xlink:href="#svg-nav-pan">
            </use>
        </svg>
        <div class="btn-name">
            抓手
        </div>
    </div>
    <div class="nav-split" style="margin-right: 17px;">
    </div>
    <div class="screen-adapter-container">
        <div class="nav-btn more-tool small" id="more-tool">
            <svg class="nav-icon">
                <use class="nav-icon-use" xlink:href="#more-tool-icon">
                </use>
            </svg>
        </div>
        <div class="screen-adapter">        
            <div class="nav-btn small-screen-hide" style="margin-right: 17px;" data-type="pencielSize">
                <div class="popover-button dropdown-toggle popover_toolbar_no_auto_dismiss CmApp-Bar-tool_icon_button_group" data-toggle="button" id="CmApp-Brush-Popover-Button">
                    <svg class="nav-icon">
                        <use class="nav-icon-use" xlink:href="#svg-nav-brush">
                        </use>
                    </svg>
                    <span>
                        笔刷大小
                    </span>
                </div>
                <!-- 笔刷大小 -->
                <div class="popover top in control-popover exclusive-group CmApp-tool_popover popover_toolbar_no_auto_dismiss" id="CmApp-Brush-Popover-Popover">
                    <div class="CmApp-tool_popover_content" id="CmApp-Brush-Popover-Content">
                        <div class="popover-toolbar CmApp-Bar-popover_settings" style="height: 30px; white-space: nowrap;">
                            <div class="CmApp-Tools-label">
                                <span>
                                    刷子尺寸：
                                </span>
                                <span class="CmApp-Brush-Size-display CmApp-Brush-brush_size_inner_display">
                                    20px
                                </span>
                            </div>
                            <div class="app_bttn_group brushBtnGroup" style="margin-right: 5px;">
                                <div class="CmApp-Brush-Size-decrease brushBtn" title="缩小刷子尺寸([)">
                                    <svg class="nav-icon" style="fill: #000;margin-right: 0;">
                                        <use class="nav-icon-use" xlink:href="#svg-nav-brushSmall">
                                        </use>
                                    </svg>
                                </div>
                                <div class="splitLine">
                                </div>
                                <div class="CmApp-Brush-Size-increase brushBtn" title="增大刷子尺寸(])">
                                    <svg class="nav-icon" style="fill: #000;margin-right: 0;">
                                        <use class="nav-icon-use" xlink:href="#svg-nav-brushBig">
                                        </use>
                                    </svg>
                                </div>
                            </div>
                            <div class="app_bttn_group">
                                <div class="CmApp-Brush-brush_size_button brushBtnSize" data-size="5">
                                    5px
                                </div>
                                <div class="CmApp-Brush-brush_size_button brushBtnSize" data-size="10">
                                    10px
                                </div>
                                <div class="CmApp-Brush-brush_size_button brushBtnSize" data-size="20">
                                    20px
                                </div>
                                <div class="CmApp-Brush-brush_size_button brushBtnSize" data-size="30">
                                    30px
                                </div>
                                <div class="CmApp-Brush-brush_size_button brushBtnSize" data-size="40">
                                    40px
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="nav-btn small-screen-hide" style="
            margin-left: 10px;
        " >
                <div class="popover_toolbar_no_auto_dismiss dropdown-menu-right">
                    <div class="popover-button dropdown-toggle CmApp-Bar-tool_icon_button_group nav-btn" data-type="backgroundColor" data-toggle="button" id="CmApp-BgColor-Popover-Button">
                        <div  style="position:relative;margin-right: 7px;">
                            <div class="background-color-swatch-container">
                                <span class="yo-data-uri checker-svg background-color-swatch swatch popover-button-label">
                                </span>
                            </div>
                            <span class="popover-button-label swatch background-color-swatch" id="CmApp-BgColor-CurrentColor">
                            </span>
                        </div>
                        <span>
                            背景颜色
                        </span>
                    </div>
                </div>
                <!-- 背景颜色 -->
                <div class="popover top in control-popover exclusive-group CmApp-tool_popover popover_toolbar_no_auto_dismiss" id="CmApp-BgColor-Popover-Popover">
                    <div class="CmApp-tool_popover_content" id="CmApp-BgColor-Popover-Content">
                        <div class="popover-toolbar CmApp-Bar-popover_settings" style="height: 30px;">
                            <div class="CmApp-Tools-label">
                                <span>
                                    背景颜色：
                                </span>
                            </div>
                            <div class="CmApp-BgColor-picker_group" data-toggle="buttons">
                                <label class="background-color-swatch-button CmApp-Tools-tool CmApp-Tools-tool_radio_button" data-color="rgba(255,255,255,0.000000)" id="background-color-swatch-button-255-255-255-0" title="透明">
                                    <input name="app-radio-bg" type="radio" value="app-radio-bg-255-255-255-0"/>
                                    <div class="background-color-swatch-container">
                                        <span class="yo-data-uri checker-svg background-color-swatch swatch popover-button-label">
                                        </span>
                                    </div>
                                </label>
                                <label class="background-color-swatch-button CmApp-Tools-tool CmApp-Tools-tool_radio_button" data-color="rgba(255,255,255,1.000000)" id="background-color-swatch-button-255-255-255-255">
                                    <input name="app-radio-bg" type="radio" value="app-radio-bg-255-255-255-255"/>
                                    <div class="background-color-swatch-container">
                                        <span class="background-color-swatch swatch popover-button-label" style="background-color: #fff;">
                                        </span>
                                    </div>
                                </label>
                                <label class="background-color-swatch-button CmApp-Tools-tool CmApp-Tools-tool_radio_button" data-color="rgba(128,128,128,1.000000)" id="background-color-swatch-button-128-128-128-255">
                                    <input name="app-radio-bg" type="radio" value="app-radio-bg-128-128-128-255"/>
                                    <div class="background-color-swatch-container">
                                        <span class="background-color-swatch swatch popover-button-label" style="background-color: #808080;">
                                        </span>
                                    </div>
                                </label>
                                <label class="background-color-swatch-button CmApp-Tools-tool CmApp-Tools-tool_radio_button" data-color="rgba(0,0,0,1.000000)" id="background-color-swatch-button-0-0-0-255">
                                    <input name="app-radio-bg" type="radio" value="app-radio-bg-0-0-0-255"/>
                                    <div class="background-color-swatch-container">
                                        <span class="background-color-swatch swatch popover-button-label" style="background-color: #000;">
                                        </span>
                                    </div>
                                </label>
                                <label class="background-color-swatch-button CmApp-Tools-tool CmApp-Tools-tool_radio_button" data-color="rgba(166,85,55,1.000000)" id="background-color-swatch-button-166-85-55-255">
                                    <input name="app-radio-bg" type="radio" value="app-radio-bg-166-85-55-255"/>
                                    <div class="background-color-swatch-container">
                                        <span class="background-color-swatch swatch popover-button-label" style="background-color: #a65537;">
                                        </span>
                                    </div>
                                </label>
                                <label class="background-color-swatch-button CmApp-Tools-tool CmApp-Tools-tool_radio_button" data-color="rgba(166,137,55,1.000000)" id="background-color-swatch-button-166-137-55-255">
                                    <input name="app-radio-bg" type="radio" value="app-radio-bg-166-137-55-255"/>
                                    <div class="background-color-swatch-container">
                                        <span class="background-color-swatch swatch popover-button-label" style="background-color: #a68937;">
                                        </span>
                                    </div>
                                </label>
                                <label class="background-color-swatch-button CmApp-Tools-tool CmApp-Tools-tool_radio_button" data-color="rgba(63,149,49,1.000000)" id="background-color-swatch-button-63-149-49-255">
                                    <input name="app-radio-bg" type="radio" value="app-radio-bg-63-149-49-255"/>
                                    <div class="background-color-swatch-container">
                                        <span class="background-color-swatch swatch popover-button-label" style="background-color: #3f9531;">
                                        </span>
                                    </div>
                                </label>
                                <label class="background-color-swatch-button CmApp-Tools-tool CmApp-Tools-tool_radio_button" data-color="rgba(137,174,200,1.000000)" id="background-color-swatch-button-137-174-200-255">
                                    <input name="app-radio-bg" type="radio" value="app-radio-bg-137-174-200-255"/>
                                    <div class="background-color-swatch-container">
                                        <span class="background-color-swatch swatch popover-button-label" style="background-color: #89aec8;">
                                        </span>
                                    </div>
                                </label>
                                <div style="margin: 0 8px; width: 1px; height: 30px; background-color: rgba(0,0,0,.08);">
                                </div>
                                <label class="background-color-swatch-button CmApp-Tools-tool CmApp-Tools-tool_radio_button" data-color="" id="background-color-swatch-button-custom">
                                    <input name="app-radio-bg" type="radio" value="app-radio-bg-custom"/>
                                    <div class="background-color-swatch-container">
                                        <span class="background-color-swatch swatch popover-button-label" style="background-color: #90a2e0;">
                                        </span>
                                    </div>
                                </label>
                            </div>
                            <input class="form-control" id="color-picker-color" name="color-picker-color" type="text" value="#90a2e0"/>
                            <div class="popover bottom" id="color-picker-ui-popover" style="bottom: auto;height:230px;top:50px">
                                <div class="arrow">
                                </div>
                                <div class="popover-content">
                                    <div id="color-picker-ui">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="nav-split small-screen-hide" style="
            margin-right: 11px;margin-left: 16px;
        ">
            </div>
            <div alt="放大（鼠标滚轮）" class="nav-btn small CmApp-Tools-zoom_in has-tips small-screen-hide" id="CmApp-Tools-zoom_in" data-type="zoomIn"  tips="放大（鼠标滚轮）">
                <svg class="nav-icon">
                    <use class="nav-icon-use" xlink:href="#svg-nav-fd">
                    </use>
                </svg>
            </div>
            <div alt="缩小（鼠标滚轮）" class="nav-btn small CmApp-Tools-zoom_out has-tips small-screen-hide" id="CmApp-Tools-zoom_out" data-type="zoomOut" tips="缩小（鼠标滚轮）">
                <svg class="nav-icon">
                    <use class="nav-icon-use" xlink:href="#svg-nav-sx">
                    </use>
                </svg>
            </div>
            <div class="nav-btn small CmApp-Tools-zoom_to_fit has-tips small-screen-hide" id="CmApp-Tools-zoom_to_fit" tips="最佳视图（Home）" data-type="zoomToFit">
                <svg class="nav-icon">
                    <use class="nav-icon-use" xlink:href="#svg-nav-best">
                    </use>
                </svg>
            </div>
        </div>
    </div>
    <div class="nav-middle">
        <div class="help-btn btn" id="help-btn">
            <svg class="btn-icon">
                <use class="nav-icon-use" xlink:href="#svg-help-icon">
                </use>
            </svg>
            <span class="btn-label btn-label-hasIcon">教程</span>
        </div>
        <div class="nav-split" style="margin-right: 16px;margin-left:0px;">
        </div>
        <div class="reset-koutu-btn btn CmApp-Tools-clear_user_mask_tool has-tips" tips="恢复原图" id="reset-koutu-btn">
            <svg class="btn-icon">
                <use class="nav-icon-use" xlink:href="#reset-koutu-icon">
                </use>
            </svg>
            <span class="btn-label btn-label-hasIcon">还原</span>
        </div>
    </div>
    <div class="nav-right">
        <label class="btn btn-compound has-tips" tips="上传原图" id="uploadOriginal">
            <svg class="btn-icon">
                <use class="nav-icon-use" xlink:href="#svg-nav-upload">
                </use>
            </svg>
            <span class="btn-label btn-label-hasIcon" for="addPic">上传</span>
            <input  id="addPic" type="file" accept="image/jpg,image/jpeg,image/png" style="display:none;">
        </label>
        <div class="file-menu popup-menu">
            <div class="download-menu" id="ktDownload" data-type="popupDownload">
                <div class="btn btn-compound" style="position: relative;">
                    <svg class="btn-icon">
                        <use xlink:href="#svg-nav-download">
                        </use>
                    </svg>
                    <label class="btn-label btn-label-hasIcon">
                        下载
                    </label>
                </div>
            </div>
            <div class="menu-popup file-menu-popup" id="ktDownloadBody">
                <div class="file-btn file-btn-save CmApp-Tools-download" id="CmApp-Tools-download">
                    <svg class="nav-icon">
                        <use class="nav-icon-use" xlink:href="#svg-nav-downloadpc">
                        </use>
                    </svg>
                    <div class="file-des">
                        本地
                    </div>
                </div>
                <div class="file-btn file-btn-save" id="CmApp-Tools-downloadkt">
                    <svg class="nav-icon">
                        <use class="nav-icon-use" xlink:href="#svg-nav-downloadkt">
                        </use>
                    </svg>
                    <div class="file-des">
                        我的素材
                    </div>
                </div>
            </div>
        </div>

       <!-- <div class="btn has-tips nav-btn-close btn-common" style="padding: 0;" id="reload" tips="关闭页面" data-type="closePage">
            <svg class="btn-icon">
                <use xlink:href="#svg-nav-close">
                </use>
            </svg>
        </div> -->
    </div>
</div>